#!/usr/bin/env bash
if [[ ! -n "$1" ]] ; then
    echo "I need domain or directory name in /var/www.";
    exit;
fi
HTTPDUSER=`ps axo user,comm | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | head -1 | cut -d\  -f1`
sudo setfacl -R -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX /var/www/$1/app/cache /var/www/$1/app/logs
sudo setfacl -dR -m u:"$HTTPDUSER":rwX -m u:`whoami`:rwX /var/www/$1/app/cache /var/www/$1/app/logs
